#!/usr/bin/env bash
# The restore stage and uninstall.sh are inverses: restore -> uninstall
# returns $HOME to what it was, file for file, driven only by the manifest.
#
# scope-d slot D (.claude/tasks/scope-d-verification-harvest.md, decisions
# 5, 6 and 8). The manifest is hand-maintained: every writer in
# scripts/install-restore*.sh must remember to claim what it creates, and a
# forgotten claim is silent — uninstall simply never removes that file. This
# test is what notices. It found one on its first run: mimeinfo.cache, which
# the installer wrote and never claimed, and which uninstall's own
# desktop-database refresh then re-created.
#
# Two scenarios, each: snapshot -> restore TWICE (a re-run must stay a no-op,
# CLAUDE.md rule 1) -> uninstall --yes -> snapshot, then compare.
#   * fresh    — an empty HOME, i.e. a new machine;
#   * lived-in — HOME already holds a tmux config (symlinks.sh must back it up
#     and uninstall must put it back byte-for-byte), a dunstrc, a .gtkrc-2.0
#     and a .zshenv. The dunstrc and .gtkrc-2.0 are then overwritten the way
#     the first wallpaper apply would, and uninstall must restore the user's
#     originals from the THEMEBACKUP copies. This scenario found that uninstall never did: the rows did not
#     record where the copy went (fixed 2026-09-28).
#
# THE DOCUMENTED LEFTOVERS. docs/UNINSTALL.md, "What's kept, always", decides
# that uninstall leaves the ZDOTDIR line in ~/.zshenv and the zinit/TPM
# clones (confirmed by the user 2026-09-28). They are asserted EXACTLY — the
# .zshenv must be its old content plus that one line, the clones must exist —
# not ignored, and each must still be named in that doc section, so the
# exception and its justification cannot drift apart. Anything else left
# behind fails. So does dots-uninstall.log being missing: it is what
# `--yes` answers to "keep a copy of the log?", so its absence means the
# uninstall never reached its last step.
#
# Directories are compared out: see snapshot() in tests/lib/install-symmetry.sh.
# Package, service, shell and suckless rows need root and are not produced by
# the restore stage; .github/workflows/install-container.yml covers those.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue() { printf '\033[34m%s\033[0m\n' "$*"; }

# shellcheck source=lib/install-symmetry.sh
source "$SCRIPT_DIR/lib/install-symmetry.sh"

rc=0
pass() { green "  ok: $1"; }
fail() {
    red "  FAIL: $1"
    rc=1
}

TMP="$(mktemp -d)"
trap 'rm -rf -- "$TMP"' EXIT
make_fakes

# The exact line install-restore.sh appends, read from the installer itself.
ZDOTDIR_LINE="$(sed -n "s/^    printf '%s\\\\n' '\\(export ZDOTDIR=.*\\)' >>\"\$ZSHENV\"\$/\\1/p" \
    "$DOTS_DIR/scripts/install-restore.sh")"
[[ -n "$ZDOTDIR_LINE" ]] || {
    red "could not read the ZDOTDIR line out of scripts/install-restore.sh"
    exit 1
}

blue "==> documented leftovers are still documented"
kept="$(sed -n '/^## What.s kept, always/,/^## /p' "$DOTS_DIR/docs/UNINSTALL.md")"
for term in ZDOTDIR zinit TPM; do
    if grep -q "$term" <<<"$kept"; then
        pass "UNINSTALL.md keeps '$term' on purpose"
    else
        fail "UNINSTALL.md's 'What's kept' no longer mentions '$term' — the exception below has lost its justification"
    fi
done

seed_lived_in() {
    local h="$1"
    mkdir -p "$h/.config/tmux" "$h/.config/dunst"
    printf 'set -g mouse on  # the user own tmux config\n' >"$h/.config/tmux/tmux.conf"
    printf '[global]\nfont = Monospace 9\n' >"$h/.config/dunst/dunstrc"
    printf 'gtk-font-name = "Sans 9"\n' >"$h/.gtkrc-2.0"
    printf 'export EDITOR=vi\n' >"$h/.zshenv"
}

# <name> <seed function or ''>
round_trip() {
    local name="$1" seed="$2" home="$TMP/$1/home" manifest before
    mkdir -p "$home"
    [[ -n "$seed" ]] && "$seed" "$home"
    blue "==> $name: restore x2 -> uninstall --yes"
    snapshot "$home" >"$TMP/$name.before"
    before=""
    [[ -f "$home/.zshenv" ]] && before="$(cat "$home/.zshenv")"

    for run in 1 2; do
        if in_sandbox "$home" "$DOTS_DIR/scripts/install-restore.sh" >"$TMP/$name.restore$run.log" 2>&1; then
            pass "restore run $run exits 0"
        else
            fail "restore run $run failed — see below"
            tail -15 "$TMP/$name.restore$run.log"
            return 0
        fi
        manifest="$home/.local/state/dots/manifest"
        cp "$manifest" "$TMP/$name.manifest$run"
    done
    check_manifest "$name"
    # What the first wallpaper apply does to a config the user already had:
    # the engine rewrites it wholesale. Uninstall must bring the original back.
    if [[ "$name" == lived-in ]]; then
        printf '# generated by the theming engine\n' >"$home/.config/dunst/dunstrc"
    fi
    # gtk2.dcol's post-command writes ~/.gtkrc-2.0 on every apply, in both
    # scenarios (decision 8: written here, never by running the engine). On a
    # fresh HOME uninstall must remove it; on a lived-in one, restore theirs.
    printf '# generated by the theming engine\n' >"$home/.gtkrc-2.0"

    if in_sandbox "$home" "$DOTS_DIR/scripts/uninstall.sh" --yes >"$TMP/$name.uninstall.log" 2>&1; then
        pass "uninstall --yes exits 0"
    else
        fail "uninstall --yes failed"
        tail -15 "$TMP/$name.uninstall.log"
    fi
    check_leftovers "$name" "$home" "$before"
}

claims() { grep -vE '^(#|META	)' "$1" | sort; }

check_manifest() {
    local name="$1" cat
    # A restore that silently did nothing would round-trip perfectly; require
    # that it actually claimed something in each category it writes.
    for cat in CONFIG SCRIPT THEME APP; do
        if grep -q "^$cat	" "$TMP/$name.manifest2"; then
            pass "manifest has $cat rows"
        else
            fail "manifest has no $cat rows — the restore did less than it should"
        fi
    done
    # META rows (version/commit/date) are rewritten by every run, so only the
    # claims are compared, order-independently.
    if diff <(claims "$TMP/$name.manifest1") <(claims "$TMP/$name.manifest2") >"$TMP/$name.mdiff"; then
        pass "a second restore claims nothing new (rule 1: re-runs are no-ops)"
    else
        fail "the second restore changed the manifest's claims:"
        sed 's/^/     /' "$TMP/$name.mdiff"
    fi
}

check_leftovers() {
    local name="$1" home="$2" before="$3" want got
    if [[ -f "$home/dots-uninstall.log" ]]; then
        pass "uninstall reached its last step (kept its log, as --yes answers)"
    else
        fail "no dots-uninstall.log — uninstall stopped before its final step"
    fi
    want="$(printf '%s%s%s' "$before" "${before:+$'\n'}" "$ZDOTDIR_LINE")"
    got="$(cat "$home/.zshenv" 2>/dev/null || true)"
    if [[ "$got" == "$want" ]]; then
        pass ".zshenv is its old content plus exactly the ZDOTDIR line (documented)"
    else
        fail ".zshenv is not old-content + ZDOTDIR line; got: $(printf '%q' "$got")"
    fi
    for clone in zinit/zinit.git tmux/plugins/tpm; do
        if [[ -f "$home/.local/share/$clone/.git/HEAD" ]]; then
            pass "$clone clone kept (documented)"
        else
            fail "$clone clone missing — the documented leftover changed; update UNINSTALL.md or this test"
        fi
    done

    snapshot "$home" | grep -vE '^\./(dots-uninstall\.log|\.zshenv|\.local/share/(zinit/zinit\.git|tmux/plugins/tpm)/)' \
        >"$TMP/$name.after" || true
    grep -vE '^\./\.zshenv ' "$TMP/$name.before" >"$TMP/$name.before.cmp" || true
    if diff "$TMP/$name.before.cmp" "$TMP/$name.after" >"$TMP/$name.diff"; then
        pass "every other file is back exactly as it was"
    else
        fail "uninstall did not reverse the restore ('>' = left behind, '<' = lost or changed):"
        sed 's/^/     /' "$TMP/$name.diff"
    fi
}

round_trip fresh ""
round_trip lived-in seed_lived_in

blue "==> nothing reached the real system"
if [[ -s "$SENTINEL_LOG" ]]; then
    fail "a sentinel command ran (sudo/dnf/systemctl/chsh/usermod/pkill/xrdb):"
    sed 's/^/     /' "$SENTINEL_LOG"
else
    pass "no sudo, dnf, systemctl, chsh, usermod, pkill or xrdb call"
fi
real_manifest="${XDG_STATE_HOME:-$HOME/.local/state}/dots/manifest"
if [[ -f "$real_manifest" ]] && grep -qF "$TMP" "$real_manifest"; then
    fail "the REAL manifest ($real_manifest) gained rows under $TMP — sandbox leaked"
else
    pass "the real manifest holds no sandbox rows"
fi

if ((rc != 0)); then
    red "✗ restore and uninstall are not inverses"
    exit 1
fi
green "✓ install/uninstall symmetry: both scenarios round-trip, documented leftovers exact"
