#!/usr/bin/env bash
# Sandbox for tests/doctor.sh — SOURCED, never run on its own (tests/lib/ is
# outside run-tests.sh's depth-1 glob). Builds a HOME that looks like a
# healthy install and a sealed PATH of fakes whose answers are steered by
# FAKE_* variables. Reads the caller's SB and DOTS_DIR.

# shellcheck source=sealed-path.sh
source "$(dirname "${BASH_SOURCE[0]}")/sealed-path.sh"
# shellcheck source=fake-flatpak.sh
source "$(dirname "${BASH_SOURCE[0]}")/fake-flatpak.sh"

# The daemon names, read the way doctor-session.sh reads them: from the
# installer's report against a file that mentions nothing.
daemon_names() {
    (
        # shellcheck disable=SC2317,SC2329 # called from the sourced report
        green() { :; }
        # shellcheck disable=SC2317,SC2329
        yellow() { printf '%s\n' "$*"; }
        # shellcheck source=../../scripts/install-session-report.sh
        source "$DOTS_DIR/scripts/install-session-report.sh"
        session_autostart_report /dev/null
    ) | sed -n 's/.*does not mention \([A-Za-z0-9._-]*\).*/\1/p'
}

make_fakes() {
    BIN="$SB/bin"
    seal_path "$BIN" bash sed grep awk tr cut cat head readlink dirname basename \
        ls sort id date mkdir touch mktemp mv cp
    # shellcheck disable=SC2016 # the bodies expand when the fakes run
    {
        fake "$BIN" rpm 'rc=0; shift 2; for p in "$@"; do
    case " ${FAKE_MISSING:-} " in *" $p "*) echo "no package provides $p"; rc=1 ;; *) echo "$p-1.0" ;; esac
done; exit $rc'
        fake "$BIN" pgrep 'case "$1" in
-x) [[ "$2" == dwm && -z "${FAKE_NO_DWM:-}" ]] ;;
-a) echo "42 picom --backend xrender" ;;
-f) for d in ${FAKE_DOWN:-}; do [[ "$2" == *"/)$d( "* ]] && exit 1; done; exit 0 ;;
*) exit 1 ;;
esac'
        fake "$BIN" xrdb 'echo "dwm.normbgcolor:	#1e1e2e"'
        fake "$BIN" pamixer 'echo 40'
        fake "$BIN" nmcli 'echo connected'
        fake "$BIN" systemctl 'echo "${FAKE_SERVICE:-enabled}"'
        fake "$BIN" getent 'echo "probe:x:1000:1000::/home/probe:/usr/bin/zsh"'
        fake "$BIN" dconf "echo \"'prefer-dark'\""
        fake "$BIN" systemd-detect-virt '[[ -z "${FAKE_NOT_VM:-}" ]]'
    }
    fake_flatpak "$BIN/flatpak" "$SB/fp"
    local d
    for d in "${DAEMONS[@]}"; do
        [[ -e "$BIN/$d" ]] || fake "$BIN" "$d" 'exit 0'
    done
}

# A HOME the installer would leave behind, plus everything a login adds.
make_home() {
    H="$SB/home"
    mkdir -p "$H/.local/state/dots" "$H/.local/bin" "$H/.cache/dots/theme" \
        "$H/.local/share/dwm" "$H/.config" "$SB/bt/hci0"
    # Written by the installer's own manifest functions, never by hand: a
    # hand-written SERVICE row once had a field the real one lacks, and the
    # service check passed here while it could never run on a real install.
    (
        XDG_STATE_HOME="$H/.local/state"
        # shellcheck source=../../scripts/global_fn.sh
        source "$DOTS_DIR/scripts/global_fn.sh"
        manifest_set_meta version "$(tr -d '[:space:]' <"$DOTS_DIR/VERSION")"
        manifest_append_row SERVICE ly@tty2.service
    )
    # The Flatpak grants and remote, the GTK3 settings.ini and the
    # Adwaita-dark shim — each written by the installer's own function.
    # shellcheck disable=SC2016 # the -c script expands in the sandbox shell
    env -i PATH="$BIN" HOME="$H" XDG_DATA_HOME="$H/.local/share" XDG_STATE_HOME="$H/.local/state" \
        XDG_CONFIG_HOME="$H/.config" DOTS_DIR="$DOTS_DIR" DRY_RUN=0 "$(type -P bash)" -c 'set -euo pipefail
        green() { :; }; yellow() { echo "$*" >&2; }; blue() { :; }
        source "$0/scripts/global_fn.sh"; source "$0/scripts/install-restore-flatpak.sh"
        source "$0/scripts/install-restore-theme.sh"; CONF_HOME="$XDG_CONFIG_HOME"
        restore_flatpak; theme_write_gtk_ini; restore_gtk3_shim' "$DOTS_DIR" >/dev/null
    ln -s "$DOTS_DIR/scripts/dots" "$H/.local/bin/dots"
    local src dst
    while IFS=$'\t' read -r src dst; do
        ln -s "$src" "$dst"
    done < <(HOME="$H" bash "$DOTS_DIR/scripts/symlinks.sh" --list-links)
    : >"$H/.cache/dots/theme/xresources"
    printf '#!/bin/sh\n' >"$H/.fehbg" && chmod +x "$H/.fehbg"
    printf '# Generated by scripts/theme/apply-templates.sh — DO NOT EDIT.\n' >"$H/.gtkrc-2.0"
    printf '%s &\n' "${DAEMONS[@]}" >"$H/.local/share/dwm/autostart.sh"
    : >"$SB/fedora-release"
}

# run_doctor [args...] — FAKE_* and DISPLAY pass through from the caller.
run_doctor() {
    env -i PATH="$BIN" HOME="$H" USER=probe DISPLAY="${DISPLAY_SET-:9}" \
        XDG_CONFIG_HOME="$H/.config" XDG_CACHE_HOME="$H/.cache" \
        XDG_STATE_HOME="$H/.local/state" XDG_DATA_HOME="$H/.local/share" \
        DOTS_DOCTOR_RELEASE="${RELEASE-$SB/fedora-release}" DOTS_DOCTOR_BT_SYSFS="$SB/bt" \
        FAKE_MISSING="${FAKE_MISSING:-}" FAKE_DOWN="${FAKE_DOWN:-}" \
        FAKE_NO_DWM="${FAKE_NO_DWM:-}" FAKE_SERVICE="${FAKE_SERVICE:-}" \
        FAKE_NOT_VM="${FAKE_NOT_VM:-}" \
        "$(type -P bash)" "$DOTS_DIR/scripts/doctor.sh" "$@"
}
